"""added Activity_Logs table

Revision ID: c4ff39208788
Revises: 497729eea7dc
Create Date: 2025-11-01 16:17:04.038666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ff39208788'
down_revision: Union[str, Sequence[str], None] = '497729eea7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.Enum('USER_LOGIN', 'USER_LOGOUT', 'USER_REGISTER', 'USER_PASSWORD_CHANGE', 'USER_PASSWORD_RESET', 'USER_EMAIL_CHANGE', 'USER_PROFILE_UPDATE', 'WEBSITE_CREATE', 'WEBSITE_DELETE', 'WEBSITE_SUSPEND', 'WEBSITE_ACTIVATE', 'WEBSITE_UPDATE', 'WEBSITE_MIGRATE', 'WP_INSTALL', 'WP_UPDATE', 'WP_PLUGIN_INSTALL', 'WP_PLUGIN_UPDATE', 'WP_PLUGIN_DELETE', 'WP_PLUGIN_ACTIVATE', 'WP_PLUGIN_DEACTIVATE', 'WP_THEME_INSTALL', 'WP_THEME_UPDATE', 'WP_THEME_DELETE', 'WP_THEME_ACTIVATE', 'BACKUP_CREATE', 'BACKUP_DELETE', 'BACKUP_RESTORE', 'BACKUP_DOWNLOAD', 'SSL_INSTALL', 'SSL_RENEW', 'SSL_REMOVE', 'FIREWALL_ENABLE', 'FIREWALL_DISABLE', 'MALWARE_SCAN', 'MALWARE_DETECTED', 'MALWARE_CLEANED', 'PHP_VERSION_CHANGE', 'CACHE_CLEAR', 'CACHE_ENABLE', 'CACHE_DISABLE', 'ADMIN_SETTING_CHANGE', 'ADMIN_USER_CREATE', 'ADMIN_USER_DELETE', 'ADMIN_USER_ROLE_CHANGE', name='activitytype'), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='activitylevel'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_activity_type'), 'activity_logs', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_website_id'), 'activity_logs', ['website_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_website_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_activity_type'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
